lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: GFM
title: A 不知所云的 blog
description: 鲁迅说：“我没说过任何一句话！”
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
