lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: GFM
title: Scott's homepage
description: Bookmark this to keep an eye on my project updates!
remote_theme: pages-themes/cayman@v0.2.0

